[package]
name = "game-rust"
version = "0.1.67"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "*"
# rand = "*"
quad-rand = { version = "0.2", features = ["rand"] }
console_error_panic_hook = "*"


